repos:
- repo: https://github.com/python-black/black
  rev: stable
  hooks:
    - id: black
- repo: https://github.com/pycodestyle/flake8
  rev: master
  hooks:
    - id: flake8
- repo: https://github.com/timothycrosley/isort
  rev: main
  hooks:
    - id: isort