version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: appointments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: bash -c "sleep 10 && python -m poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db
    env_file:
      - .local.env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"

volumes:
  pgdata: